### PR TITLE
Allow disabling TLS

### PR DESCRIPTION
**Pull request by michaeljs1990**
This lets you turn off TLS in cases which you may not care that TLS is valid such as for local testing.

### CODE REVIEW

**Comment by michaeljs1990** [comment]
This also adds go mod so you don't have to mess with GOPATH and such anymore.

**Comment by michaeljs1990** [comment]
```
health_checker.go:59: G402: TLS InsecureSkipVerify set true. (gas)
			InsecureSkipVerify: true,
The command "golangci-lint run" exited with 1.
```
Is what the linter is not happy about which is the point of this diff. Not sure how to disable that as running the linter locally throws a few hundred errors on the code for me.

**Comment by michaeljs1990** [comment]
This has been verified on a host now that was failing before during testing and works as expect.

1. `VAULT_HEALTH_CHECK_SKIP_VERIFY` not set and bad TLS cert causes an unhealthy report
2. `VAULT_HEALTH_CHECK_SKIP_VERIFY=random` and bad TLS cert causes an unhealthy report
3. `VAULT_HEALTH_CHECK_SKIP_VERIFY=true`  bad TLS cert causes a healthy report

**Comment by jen20** [comment]
Hi @michaeljs1990! Thanks for opening a PR - I'll get this reviewed and merged today.

**Review by jen20 — APPROVED** [review]
Hi @michaeljs1990! Thanks for the PR, sorry for the delay in getting to it. I've rebased this locally after splitting out the Go Modules work and some other housekeeping cleanup, and merged it in 643aded. I'll cut a release now.

**Comment by michaeljs1990** [comment]
Thanks for landing :)

**Comment by jen20** [comment]
@michaeljs1990 sorry it took so long - I'd accidentally unsubscribed from repo notifications... Thanks for the PR!

**Pull request closed without merging**
